package com.shutterstar.agenthub

data class CodingAgent(
    val id: String,
    val name: String,
    val command: String,
    val versionArgs: String = "--version",
    val installHint: String,
    val updateHint: String,
    val uninstallHint: String = "",
    /** Windows-specific install command; falls back to [installHint] if blank. */
    val installHintWindows: String = "",
    /** Windows-specific uninstall command; falls back to [uninstallHint] if blank. */
    val uninstallHintWindows: String = "",
    val provider: String = "",
    val url: String,
    val devUrl: String = "",
    /** No native Windows install path (WSL-only or unsupported) → hidden from the UI on Windows. */
    val unsupportedOnWindows: Boolean = false,
) {
    val platformInstallHint: String get() =
        if (OsDetector.isWindows() && installHintWindows.isNotBlank()) installHintWindows else installHint

    val platformUninstallHint: String get() =
        if (OsDetector.isWindows() && uninstallHintWindows.isNotBlank()) uninstallHintWindows else uninstallHint
}

object CodingAgents {
    /**
     * Agents enabled by default on a fresh install (in addition to any detected-installed agents).
     * Picked as the 10 most widely used CLI coding agents.
     */
    val defaultActiveIds: List<String> = listOf(
        "claude", "codex", "copilot", "cursor", "aider",
        "grok", "qwen", "goose", "opencode", "cline",
    )

    // On Windows, hide agents with no native Windows install (WSL-only / unsupported): a binary
    // installed inside WSL is invisible to the Windows-native detection (`where`) and launch.
    fun available(): List<CodingAgent> =
        if (OsDetector.isWindows()) all.filterNot { it.unsupportedOnWindows } else all

    val all: List<CodingAgent> = listOf(
        CodingAgent(
            id = "aider",
            name = "Aider",
            command = "aider",
            installHint = "pip install aider-install && aider-install",
            updateHint = "uv tool upgrade aider-chat || pipx upgrade aider-chat",
            uninstallHint = "uv tool uninstall aider-chat || pipx uninstall aider-chat || pip uninstall -y aider-chat; pip uninstall -y aider-install",
            provider = "Aider AI",
            url = "https://aider.chat",
            devUrl = "https://github.com/Aider-AI/aider",
        ),
        CodingAgent(
            id = "amp",
            name = "Amp",
            command = "amp",
            installHint = "npm install -g @sourcegraph/amp",
            updateHint = "npm update --quiet --no-fund -g @sourcegraph/amp",
            uninstallHint = "npm uninstall -g @sourcegraph/amp",
            provider = "Sourcegraph",
            url = "https://ampcode.com",
            devUrl = "https://github.com/sourcegraph/amp",
        ),
        CodingAgent(
            id = "antigravity",
            name = "Antigravity CLI",
            command = "agy",
            installHint = "curl -fsSL https://antigravity.google/cli/install.sh | bash",
            updateHint = "agy update",
            uninstallHint = "rm -f ~/.local/bin/agy",
            installHintWindows = "irm https://antigravity.google/cli/install.ps1 | iex",
            uninstallHintWindows = "Remove-Item -Recurse -Force \"\$env:LOCALAPPDATA\\Antigravity\" -ErrorAction SilentlyContinue",
            provider = "Google",
            url = "https://antigravity.google/product/antigravity-cli",
            devUrl = "https://github.com/google-antigravity/antigravity-cli",
        ),
        CodingAgent(
            id = "auggie",
            name = "Auggie",
            command = "auggie",
            installHint = "npm install -g @augmentcode/auggie",
            updateHint = "npm update --quiet --no-fund -g @augmentcode/auggie",
            uninstallHint = "npm uninstall -g @augmentcode/auggie",
            provider = "Augment",
            url = "https://www.augmentcode.com/product/CLI",
            devUrl = "https://github.com/augmentcode/auggie",
        ),
        CodingAgent(
            id = "claude",
            name = "Claude Code",
            command = "claude",
            installHint = "npm install -g @anthropic-ai/claude-code",
            updateHint = "npm update --quiet --no-fund -g @anthropic-ai/claude-code",
            uninstallHint = "npm uninstall -g @anthropic-ai/claude-code",
            provider = "Anthropic",
            url = "https://claude.com/product/claude-code",
            devUrl = "https://github.com/anthropics/claude-code",
        ),
        CodingAgent(
            id = "cline",
            name = "Cline",
            command = "cline",
            installHint = "npm install -g cline",
            updateHint = "npm update --quiet --no-fund -g cline",
            uninstallHint = "npm uninstall -g cline",
            provider = "Cline",
            url = "https://cline.bot/cli",
            devUrl = "https://github.com/cline/cline",
        ),
        CodingAgent(
            id = "codex",
            name = "Codex CLI",
            command = "codex",
            installHint = "npm install -g @openai/codex",
            updateHint = "npm update --quiet --no-fund -g @openai/codex",
            uninstallHint = "npm uninstall -g @openai/codex",
            provider = "OpenAI",
            url = "https://openai.com/codex",
            devUrl = "https://github.com/openai/codex",
        ),
        CodingAgent(
            id = "cody",
            name = "Cody CLI",
            command = "cody",
            installHint = "npm install -g @sourcegraph/cody",
            updateHint = "npm update --quiet --no-fund -g @sourcegraph/cody",
            uninstallHint = "npm uninstall -g @sourcegraph/cody",
            provider = "Sourcegraph",
            url = "https://sourcegraph.com/cody",
            devUrl = "https://github.com/sourcegraph/cody",
        ),
        CodingAgent(
            id = "continue",
            name = "Continue CLI",
            command = "cn",
            installHint = "npm install -g @continuedev/cli",
            updateHint = "npm update --quiet --no-fund -g @continuedev/cli",
            uninstallHint = "npm uninstall -g @continuedev/cli",
            provider = "Continue",
            url = "https://continue.dev",
            devUrl = "https://github.com/continuedev/continue",
        ),
        CodingAgent(
            id = "copilot",
            name = "Copilot CLI",
            command = "copilot",
            installHint = "npm install -g @github/copilot",
            updateHint = "npm update --quiet --no-fund -g @github/copilot",
            uninstallHint = "npm uninstall -g @github/copilot",
            provider = "GitHub",
            url = "https://github.com/features/copilot/cli",
            devUrl = "https://github.com/github/copilot-cli",
        ),
        CodingAgent(
            id = "crush",
            name = "Crush",
            command = "crush",
            installHint = "npm install -g @charmland/crush",
            updateHint = "npm update --quiet --no-fund -g @charmland/crush",
            uninstallHint = "npm uninstall -g @charmland/crush",
            provider = "Charm",
            url = "https://charm.land/",
            devUrl = "https://github.com/charmbracelet/crush",
        ),
        CodingAgent(
            id = "cursor",
            name = "Cursor CLI",
            command = "cursor-agent",
            installHint = "curl https://cursor.com/install -fsS | bash",
            updateHint = "cursor-agent update",
            uninstallHint = "rm -f ~/.local/bin/cursor-agent ~/.local/bin/agent && rm -rf ~/.local/share/cursor-agent",
            installHintWindows = "irm 'https://cursor.com/install?win32=true' | iex",
            // Windows installer puts everything under %LOCALAPPDATA%\cursor-agent (not ~/.local/bin like Unix).
            uninstallHintWindows = "Remove-Item -Recurse -Force \"\$env:LOCALAPPDATA\\cursor-agent\" -ErrorAction SilentlyContinue",
            provider = "Cursor",
            url = "https://cursor.com/cli",
        ),
        CodingAgent(
            id = "droid",
            name = "Droid",
            command = "droid",
            installHint = "npm install -g droid",
            updateHint = "npm update --quiet --no-fund -g droid",
            uninstallHint = "npm uninstall -g droid",
            provider = "Factory AI",
            url = "https://factory.ai/product/ide",
            devUrl = "https://github.com/Factory-AI/factory",
        ),
        CodingAgent(
            id = "forge",
            name = "ForgeCode",
            command = "forge",
            installHint = "curl -fsSL https://forgecode.dev/cli | sh",
            updateHint = "forge update",
            uninstallHint = "rm -f $(which forge) && rm -rf ~/.forge",
            installHintWindows = "wsl bash -c \"curl -fsSL https://forgecode.dev/cli | sh\"",
            uninstallHintWindows = "wsl bash -c \"rm -f `\$(which forge) && rm -rf ~/.forge\"",
            provider = "Antinomy",
            url = "https://forgecode.dev",
            devUrl = "https://github.com/antinomyhq/forge",
            unsupportedOnWindows = true, // WSL-only install; binary not visible to Windows-native detection
        ),
        CodingAgent(
            id = "goose",
            name = "Goose CLI",
            command = "goose",
            installHint = "curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | bash",
            updateHint = "goose update",
            uninstallHint = "brew uninstall block-goose-cli 2>/dev/null || rm -f ~/.local/bin/goose",
            // No download_cli.ps1 exists (404); fetch the native Windows CLI zip, extract, and add it to PATH.
            installHintWindows = "Invoke-WebRequest 'https://github.com/block/goose/releases/download/stable/goose-x86_64-pc-windows-msvc.zip' -OutFile \"\$env:TEMP\\goose.zip\"; Expand-Archive -Force \"\$env:TEMP\\goose.zip\" \"\$env:LOCALAPPDATA\\goose\"; \$p=[Environment]::GetEnvironmentVariable('Path','User'); if(\$p -notlike '*goose\\goose-package*'){[Environment]::SetEnvironmentVariable('Path',\"\$env:LOCALAPPDATA\\goose\\goose-package;\$p\",'User')}",
            uninstallHintWindows = "Remove-Item -Recurse -Force \"\$env:LOCALAPPDATA\\goose\" -ErrorAction SilentlyContinue",
            provider = "Block",
            url = "https://block.github.io/goose",
            devUrl = "https://github.com/block/goose",
        ),
        CodingAgent(
            id = "grok",
            name = "Grok Build",
            command = "grok",
            installHint = "curl -fsSL https://x.ai/cli/install.sh | bash",
            updateHint = "grok update",
            uninstallHint = "rm -rf ~/.grok && rm -f $(which grok)",
            installHintWindows = "irm https://x.ai/cli/install.ps1 | iex",
            uninstallHintWindows = "Remove-Item -Recurse -Force \"\$env:USERPROFILE\\.grok\" -ErrorAction SilentlyContinue",
            provider = "xAI",
            url = "https://x.ai/cli",
        ),
        CodingAgent(
            id = "kilo",
            name = "Kilo Code",
            command = "kilo",
            installHint = "npm install -g @kilocode/cli",
            updateHint = "npm update --quiet --no-fund -g @kilocode/cli",
            uninstallHint = "npm uninstall -g @kilocode/cli",
            provider = "Kilo",
            url = "https://kilo.ai",
            devUrl = "https://github.com/Kilo-Org/kilocode",
        ),
        CodingAgent(
            id = "kimi",
            name = "Kimi Code",
            command = "kimi",
            installHint = "pip install kimi-cli",
            updateHint = "pip install --upgrade --upgrade-strategy eager kimi-cli",
            uninstallHint = "pip uninstall -y kimi-cli",
            provider = "Moonshot AI",
            url = "https://www.kimi.com/code",
            devUrl = "https://github.com/MoonshotAI/kimi-cli",
        ),
        CodingAgent(
            id = "kiro",
            name = "Kiro CLI",
            command = "kiro-cli",
            installHint = "curl -fsSL https://cli.kiro.dev/install | bash",
            updateHint = "kiro-cli update",
            uninstallHint = "kiro-cli uninstall || rm -f ~/.local/bin/kiro-cli ~/.local/bin/kiro-cli-chat",
            installHintWindows = "irm 'https://cli.kiro.dev/install.ps1' | iex",
            uninstallHintWindows = "kiro-cli uninstall",
            provider = "Kiro",
            url = "https://kiro.dev/cli/",
            devUrl = "https://github.com/kirodotdev/Kiro",
        ),
        CodingAgent(
            id = "leanctl",
            name = "LeanCTL",
            command = "leanctl",
            installHint = "npm install -g leanctl-bin",
            updateHint = "npm update --quiet --no-fund -g leanctl-bin",
            uninstallHint = "npm uninstall -g leanctl-bin",
            provider = "LeanCTL",
            url = "https://leanctl.com",
            devUrl = "https://github.com/yvgude/lean-ctl",
            unsupportedOnWindows = true, // no native Windows binary (npm/releases ship macOS+Linux only)
        ),
        CodingAgent(
            id = "mimo",
            name = "MiMo Code",
            command = "mimo",
            installHint = "npm install -g @mimo-ai/cli",
            updateHint = "npm update --quiet --no-fund -g @mimo-ai/cli",
            uninstallHint = "npm uninstall -g @mimo-ai/cli",
            provider = "Xiaomi",
            url = "https://mimo.xiaomi.com/mimocode",
            devUrl = "https://github.com/XiaomiMiMo/MiMo-Code",
        ),
        CodingAgent(
            id = "vibe",
            name = "Mistral Vibe",
            command = "vibe",
            installHint = "pip install mistral-vibe",
            updateHint = "pip install --upgrade --upgrade-strategy eager mistral-vibe",
            uninstallHint = "pip uninstall -y mistral-vibe",
            provider = "Mistral AI",
            url = "https://mistral.ai/products/vibe",
            devUrl = "https://github.com/mistralai/mistral-vibe",
        ),
        CodingAgent(
            id = "opencode",
            name = "OpenCode",
            command = "opencode",
            installHint = "npm install -g opencode-ai",
            updateHint = "npm update --quiet --no-fund -g opencode-ai",
            uninstallHint = "npm uninstall -g opencode-ai",
            provider = "SST",
            url = "https://opencode.ai",
            devUrl = "https://github.com/sst/opencode",
        ),
        CodingAgent(
            id = "openhands",
            name = "OpenHands",
            command = "openhands",
            installHint = "pip install openhands-ai",
            updateHint = "pip install --upgrade --upgrade-strategy eager openhands-ai",
            uninstallHint = "pip uninstall -y openhands-ai",
            provider = "All Hands",
            url = "https://openhands.dev/",
            devUrl = "https://github.com/OpenHands/OpenHands",
        ),
        CodingAgent(
            id = "plandex",
            name = "Plandex",
            command = "plandex",
            installHint = "curl -sL https://plandex.ai/install.sh | bash",
            updateHint = "plandex upgrade",
            uninstallHint = "rm -f $(which plandex) $(which pdx)",
            installHintWindows = "wsl bash -c \"curl -sL https://plandex.ai/install.sh | bash\"",
            uninstallHintWindows = "wsl bash -c \"rm -f `$(which plandex) `$(which pdx)\"",
            provider = "Plandex",
            url = "https://plandex.ai",
            devUrl = "https://github.com/plandex-ai/plandex",
            unsupportedOnWindows = true, // WSL-only install; binary not visible to Windows-native detection
        ),
        CodingAgent(
            id = "qodo",
            name = "Qodo",
            command = "qodo",
            installHint = "npm install -g @qodo/command",
            updateHint = "npm update --quiet --no-fund -g @qodo/command",
            uninstallHint = "npm uninstall -g @qodo/command",
            provider = "Qodo",
            url = "https://qodo.ai",
            devUrl = "https://github.com/qodo-ai/command",
        ),
        CodingAgent(
            id = "qoder",
            name = "Qoder CLI",
            command = "qodercli",
            installHint = "npm install -g @qoder-ai/qodercli",
            updateHint = "npm update --quiet --no-fund -g @qoder-ai/qodercli",
            uninstallHint = "npm uninstall -g @qoder-ai/qodercli",
            provider = "Qoder AI",
            url = "https://qoder.com",
            devUrl = "https://github.com/QoderAI",
        ),
        CodingAgent(
            id = "qwen",
            name = "Qwen Code",
            command = "qwen",
            installHint = "npm install -g @qwen-code/qwen-code@latest",
            updateHint = "npm update --quiet --no-fund -g @qwen-code/qwen-code",
            uninstallHint = "npm uninstall -g @qwen-code/qwen-code",
            provider = "Alibaba",
            url = "https://qwen.ai/qwencode",
            devUrl = "https://github.com/QwenLM/qwen-code",
        ),
        CodingAgent(
            id = "sweagent",
            name = "SWE-agent",
            command = "sweagent",
            installHint = "pip install sweagent",
            updateHint = "pip install --upgrade --upgrade-strategy eager sweagent",
            uninstallHint = "pip uninstall -y sweagent",
            provider = "SWE-agent",
            url = "https://swe-agent.com",
            devUrl = "https://github.com/SWE-agent/SWE-agent",
        ),
        CodingAgent(
            id = "vtcode",
            name = "VT Code",
            command = "vtcode",
            installHint = "npm install -g @vinhnx/vtcode --registry=https://npm.pkg.github.com",
            updateHint = "npm update --quiet --no-fund -g @vinhnx/vtcode --registry=https://npm.pkg.github.com",
            uninstallHint = "npm uninstall -g @vinhnx/vtcode --registry=https://npm.pkg.github.com",
            provider = "vinhnx",
            url = "https://vinhnx.github.io/",
            devUrl = "https://github.com/vinhnx/vtcode",
        ),
    )

}